name: Deploy E221 Front Office to Vercel

on:
  push:
    branches: [main] # Using master as defaultBase from your nx.json
    paths:
      - 'apps/e221-front-office/**' # Only app changes
  pull_request:
    branches: [main]
    paths:
      - 'apps/e221-front-office/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for Nx affected commands

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Using a more recent Node version for Angular
          cache: 'npm'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      # This uses your NxCloud setup from nx.json
      - name: Nx Cloud Auth
        run: echo "Nx Cloud skipped"

      - name: Install Dependencies
        run: npm install

      - name: Build e221-front-office
        run: npx nx build e221-front-office --configuration=ci --no-cloud --verbose
        # Using the ci configuration from your project.json

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_E221_APP_PROJECT_ID }}
          working-directory: ./
          build-command: echo "skip build because already built above"
          output-directory: dist/apps/e221-front-office/browser

permissions:
  contents: read
  actions: read
  pull-requests: read
